//convert pas to utf8 by ¥
{$IFDEF WinEdit}
  TSkinWinEdit
{$ENDIF}
{$IFDEF FMXEdit}
  TSkinFMXCustomEdit
{$ENDIF}


{$IFDEF WinDateEdit}
  TSkinWinDateEdit
{$ENDIF}





{$IFDEF WinComboBox}
  TSkinWinComboBox
{$ENDIF}
{$IFDEF FMXComboBox}
  TSkinFMXCustomComboBox
{$ENDIF}
{$IFDEF FMXCustomDateEdit}
  TSkinFMXCustomDateEdit
{$ENDIF}
{$IFDEF FMXTimeEdit}
  TSkinFMXCustomTimeEdit
{$ENDIF}
{$IFDEF FMXPopup}
  TSkinFMXPopup
{$ENDIF}
{$IFDEF FMXComboEdit}
  TSkinFMXCustomComboEdit
{$ENDIF}




{$IFDEF FMXMemo}
  TSkinFMXCustomMemo
{$ENDIF}
{$IFDEF WinMemo}
  TSkinWinMemo
{$ENDIF}




{$IFDEF WinForm}
  TSkinWinForm
{$ENDIF}
{$IFDEF DUIForm}
  TSkinDUIForm
{$ENDIF}
{$IFDEF FMXForm}
  TSkinFMXForm
{$ENDIF}




{$IFDEF WinControl}
  TSkinWindowsControl
{$ENDIF}
{$IFDEF DUIControl}
  TSkinDirectUIControl
{$ENDIF}
{$IFDEF FMXControl}
  TSkinFireMonkeyControl
{$ENDIF}



{$IFDEF OUIBaseFMXControl}
  TBaseFMXControl
{$ENDIF}

